CREATE DATABASE CST8333;
USE CST8333;

-- DROP TABLE PET;

CREATE TABLE PET (
	PetID INT AUTO_INCREMENT,
	AnimalBreed VARCHAR(45),
		CHECK (AnimalBreed IN ("Alligator", "Bird", "Cat", "Chimpanzee", "Cow", "Crab", "Dog", "Donkey", "Fish", "Ferret", "Frog", "Gerbil", "Guinea Pig", 
        "Hamster", "Horse", "Insect", "Lizard", "Monkey", "Mouse", "Pig", "Rabbit", "Rat", "Spider", "Snake", "Toad", "Turtle")),
	AnimalVariety VARCHAR(45) NOT NULL,
	Size VARCHAR(45)
		CHECK (Size IN ("Small", "Medium", "Large")),
	SoundLevel VARCHAR(45)
		CHECK (SoundLevel IN ("Quiet", "Loud")),
	ActivityLevel VARCHAR(45)
		CHECK (ActivityLevel IN ("Low", "High")),
	HairLength VARCHAR(45)
		CHECK (HairLength IN ("Bald", "Short", "Long")),
	AffectionLevel VARCHAR(45)
		CHECK (AffectionLevel IN ("Warm", "Cold")),
	CONSTRAINT PK_PET PRIMARY KEY (PetID)
);


INSERT INTO PET
	(AnimalBreed, AnimalVariety, Size, SoundLevel, ActivityLevel, HairLength, AffectionLevel)
VALUES
	("Alligator", "Dwarf Caiman ", "Medium", "Quiet", "Low", "Bald", "Cold"), 
	("Bird", "African Grey Parrot", "Medium", "Loud", "Low", "Long", "Warm"),
	("Bird", "Amazon Mealy Parrot", "Medium", "Loud", "Low", "Long", "Warm"),
	("Bird", "Amazon Red-Lored", "Medium", "Quiet", "Low", "Long", "Cold"),
	("Bird", "Canary", "Small", "Quiet", "Low", "Long", "Cold"),
	("Bird", "Cockatiel", "Medium", "Quiet", "Low", "Long", "Warm"),
	("Bird", "Citron Cockatoo", "Medium", "Loud", "High", "Long", "Warm"),
	("Bird", "Palm Cockatoo", "Large", "Loud", "High", "Long", "Warm"),
	("Bird", "Dove", "Medium", "Quiet", "Low", "Long", "Cold"),
	("Bird", "Finch", "Small", "Quiet", "Low", "Long", "Cold"),
	("Bird", "Macaw", "Large", "Loud", "High", "Long", "Warm"),
	("Bird", "Alexandrine Parakeet", "Large", "Loud", "High", "Long", "Warm"),
	("Bird", "Rosella Parakeet", "Medium", "Quiet", "Low", "Long", "Cold"),
	("Bird", "Toucan", "Large", "Quiet", "Low", "Long", "Cold"),
	("Cat", "Maine Coon", "Large", "Quiet", "High", "Long", "Warm"),
	("Cat", "Munchkin", "Small", "Quiet", "High", "Long", "Warm"),
	("Cat", "Napoleon", "Small", "Quiet", "High", "Long", "Warm"),
	("Cat", "Siamese", "Small", "Quiet", "High", "Long", "Warm"),
	("Cat", "Sphinx", "Small", "Quiet", "High", "Bald", "Warm"),
	("Chimpanzee", "Chimpanzee", "Large", "Loud", "High", "Short", "Cold"), 
	("Cow", "Dexter", "Large", "Quiet", "High", "Short", "Warm"),
	("Cow", "Miniature Scottish Highland", "Large", "Quiet", "Low", "Long", "Warm"),
	("Crab", "Halloween Moon", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Crab", "Thai Devil", "Small", "Quiet", "Low", "Bald", "Warm"),
	("Crab", "Vampire", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Dog", "Chihuahua", "Small", "Loud", "High", "Short", "Warm"),
	("Dog", "Maltese", "Small", "Loud", "High", "Long", "Warm"),
	("Dog", "Pomeranian", "Small", "Loud", "High", "Long", "Warm"),
	("Dog", "Toy Poodle", "Small", "Loud", "High", "Long", "Warm"),
	("Dog", "Beagle", "Small", "Loud", "High", "Short", "Warm"),
	("Dog", "Bichon Frise", "Small", "Loud", "High", "Long", "Warm"),
	("Dog", "Corgi", "Small", "Loud", "High", "Short", "Warm"),
	("Dog", "Cocker Spaniel", "Small", "Loud", "High", "Long", "Warm"),
	("Dog", "Dachshund", "Small", "Loud", "High", "Short", "Warm"),
	("Dog", "Pug", "Small", "Quiet", "High", "Short", "Warm"),
	("Dog", "Basset Hound", "Medium", "Loud", "Low", "Long", "Warm"),
	("Dog", "Border Collie", "Medium", "Loud", "High", "Long", "Warm"),
	("Dog", "Boxer", "Medium", "Loud", "High", "Short", "Warm"),
	("Dog", "Bulldog", "Medium", "Loud", "High", "Short", "Warm"),
	("Dog", "Dalmatian", "Medium", "Loud", "High", "Short", "Warm"),
	("Dog", "Doberman Pinscher", "Medium", "Loud", "High", "Long", "Warm"),
	("Dog", "Poodle", "Medium", "Loud", "High", "Long", "Warm"),
	("Dog", "Bloodhound", "Large", "Loud", "High", "Short", "Warm"),
	("Dog", "Greyhound", "Large", "Loud", "High", "Short", "Warm"),
	("Dog", "Irish Setter", "Large", "Loud", "High", "Long", "Warm"),
	("Dog", "Rottweiler", "Large", "Quiet", "High", "Short", "Warm"),
	("Dog", "Akita", "Large", "Loud", "High", "Long", "Warm"),
	("Dog", "Great Dane", "Large", "Loud", "High", "Short", "Warm"),
	("Dog", "Mastiff", "Large", "Quiet", "High", "Short", "Warm"),
	("Dog", "Saint Bernard", "Large", "Quiet", "High", "Long", "Warm"),
	("Donkey", "Mammoth", "Large", "Loud", "High", "Short", "Warm"),
	("Donkey", "Miniature", "Medium", "Loud", "High", "Short", "Warm"),
	("Donkey", "Poitou", "Large", "Loud", "High", "Long", "Warm"),
	("Fish", "Beta", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Clown Fish", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Discusfish", "Medium", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Goldfish", "Medium", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Guppy", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Lionfish", "Medium", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Neon Tetra", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Fish", "Oscar", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Ferret", "Sable", "Small", "Loud", "High", "Long", "Warm"),
	("Ferret", "Cinnamon", "Small", "Loud", "High", "Long", "Warm"),
	("Frog", "Green Tree", "Small", "Loud", "Low", "Bald", "Cold"),
	("Frog", "Pacman", "Medium", "Loud", "Low", "Bald", "Cold"),
	("Gerbil", "Great", "Small", "Quiet", "High", "Short", "Warm"),
	("Gerbil", "Mongolian", "Small", "Quiet", "High", "Short", "Warm"),
	("Gerbil", "Pale", "Small", "Quiet", "High", "Short", "Warm"),
	("Guinea Pig", "American", "Small", "Loud", "High", "Short", "Warm"),
	("Guinea Pig", "Peruvian", "Small", "Loud", "High", "Long", "Warm"),
	("Guinea Pig", "Skinny Pig", "Small", "Loud", "High", "Bald", "Warm"),
	("Hamster", "Chinese", "Small", "Quiet", "High","Long", "Warm"),
	("Hamster", "Syrian", "Small", "Quiet", "High", "Short", "Warm"),
	("Horse", "Arabian", "Large", "Quiet", "High", "Short", "Warm"),
	("Horse", "Andalusian", "Large", "Loud", "High", "Short", "Warm"),
	("Horse", "Miniature", "Medium", "Quiet", "Low", "Long", "Warm"),
	("Horse", "Shetland Pony", "Medium", "Quiet", "High", "Long", "Warm"),
	("Insect", "Ant", "Small", "Quiet", "High", "Bald", "Cold"),
	("Insect", "Giant Millipedes", "Medium", "Quiet", "Low", "Bald", "Cold"),
	("Insect", "Emperor Scorpion", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Lizard", "Bearded Dragon", "Medium", "Quiet", "High", "Bald", "Cold"),
	("Lizard", "Green Anole", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Lizard", "Ackies Monitor", "Large", "Quiet", "Low", "Bald", "Cold"),
	("Lizard", "Veiled Chameleon", "Medium", "Quiet", "Low", "Bald", "Cold"),
	("Lizard", "Green Iguana", "Large", "Quiet", "Low", "Bald", "Cold"),
	("Monkey", "Capuchin", "Small", "Loud", "High", "Long", "Cold"),
	("Monkey", "Guenon", "Medium", "Loud", "High", "Short", "Cold"),
	("Monkey", "Squirrel", "Small", "Loud", "High", "Short", "Cold"),
	("Monkey", "Spider", "Small", "Loud", "High", "Short", "Cold"),
	("Monkey", "Tamarin", "Small", "Loud", "High", "Long", "Cold"),
	("Mouse", "Frizzie", "Small", "Quiet", "High", "Long", "Cold"),
	("Mouse", "Hairless", "Small", "Quiet", "High", "Bald", "Cold"),
	("Mouse", "Satin", "Small", "Quiet", "High", "Short", "Cold"),
    ("Pig", "Potbellied", "Medium", "Loud", "High", "Short", "Warm"),
	("Pig", "Juliana", "Small", "Loud", "High", "Short", "Warm"),
	("Pig", "Yucatan Hairless", "Large", "Loud", "High", "Bald", "Warm"),
	("Pig", "Kunekune", "Large", "Loud", "High", "Short", "Warm"),
 	("Rabbit", "American", "Medium", "Quiet", "High", "Long", "Warm"),
	("Rabbit", "Chinchilla", "Medium", "Quiet", "High", "Short", "Warm"),
	("Rabbit", "Dutch", "Small", "Quiet", "High", "Long", "Warm"),
	("Rat", "Hairless", "Small", "Quiet", "High", "Bald", "Warm"),
	("Rat", "Satin", "Small", "Quiet", "High", "Long", "Warm"), 
	("Snake", "Ball Python", "Medium", "Quiet", "Low", "Bald", "Cold"),
	("Snake", "Kenyan Sand Boa", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Snake", "Garter", "Small", "Quiet", "Low", "Bald", "Cold"),
	("Snake", "Reticulated Python", "Large", "Quiet", "Low", "Bald", "Cold"),
	("Spider", "Red Rump Tarantula", "Small", "Quiet", "Low", "Short", "Cold"),
	("Spider", "Rose Tarantula", "Small", "Quiet", "Low", "Short", "Cold"), 
	("Toad", "American ", "Small", "Loud", "High", "Bald", "Cold"),
	("Toad", "California", "Small", "Loud", "High", "Bald", "Cold"),
	("Toad", "Cane", "Small", "Loud", "High", "Bald", "Warm"),
	("Turtle", "Red-Eared Slider", "Medium", "Quiet", "Low", "Bald", "Warm"),
	("Turtle", "Sulcata", "Large", "Quiet", "High", "Bald", "Cold"),
	("Turtle", "Stinkpot", "Small", "Quiet", "Low", "Bald", "Cold");
    
    